version: "1"
aliases:
    ignore: '!gh api /gitignore/templates/$1 --jq .source | bat --language=gitignore --style=plain'
    create: repo create
    clone: repo clone
    fork: repo fork
    browse: repo view --web
