version: "1"
aliases:
    ignore: |
        !gh repo gitignore list |
        tail --lines=+2 |
        fzf --multi --preview='gh repo gitignore view {} | bat --force-colorization --language=gitignore' --prompt='Select .gitignore template(s): ' --query=$1 |
        xargs --max-args=1 gh repo gitignore view |
        bat --language=gitignore --style=plain
    clone: |
        !gh repo list --json nameWithOwner,updatedAt --jq 'sort_by(.updatedAt) | reverse | .[].nameWithOwner' |
        fzf |
        ghq get
    fork: repo fork
    browse: repo view --web
    new: |
        !fzf --preview='gh help {} create' --preview-window=right,80%,wrap << EOF |
        issue
        pr
        release
        repo
        EOF
        xargs -o --verbose -Icommand gh command create
