version: "1"
aliases:
    ignore: '!gh api /gitignore/templates/$1 --jq .source | bat --language=gitignore --style=plain'
    clone: repo clone
    fork: repo fork
    browse: repo view --web
    new: |
        !fzf << EOF |
        issue
        pr
        release
        repo
        EOF
        xargs -o --verbose -Icommand gh command create
