tap 'homebrew/bundle'

brew 'coreutils'
brew 'ffmpeg'
brew 'fzf' # or 'fzy'
brew 'ghq'
brew 'git'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'grep'
brew 'go'
brew 'hub'
brew 'nkf'
brew 'python'
brew 'tig'
brew 'tree'
brew 'vim', args: ['with-lua', 'with-luajit']
brew 'wget'
brew 'zplug'
brew 'zsh', args: ['without-etcdir']
brew 'zsh-completions'

cask install dropbox
cask install iterm2
cask install mendeley-desktop
cask install spotify
cask install vivaldi
