name: Setup fresh machine
on:
  push:
    paths:
      - '.github/workflows/setup-fresh-machine.yaml'
      - 'script/**'
      - Makefile
  schedule:
    - cron: '42 15 * * 4'
defaults:
  run:
    shell: bash
jobs:
  setup-fresh-machine:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Uninstall built-in Homebrew
        run: |
          BREW_PREFIX="$(brew --prefix)"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
          sudo rm -rf "$BREW_PREFIX"
        env:
          NONINTERACTIVE: 1
      - name: Run install command
        run: make install
